/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.droll.model;

import java.util.Calendar;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 *
 * @author rev
 */
@Entity
@Table(name = "tb_ideas") 
public class Idea {
    @Id // @Id indicates that this it a unique primary key
    @GeneratedValue // @GeneratedValue indicates that value is automatically generated by the server
    private Integer id;

    @Column(name="description" , length = 32, unique = true , nullable = false)
    private String description;

    @Column(name="user_name" )
    private String userName;
    
    @Column(name="public")
    private boolean pub;
    
    @Column(name="created")
    @Temporal(TemporalType.TIMESTAMP)
    private Calendar created;
    
    @OneToMany(fetch= FetchType.LAZY,cascade = {CascadeType.ALL})
    @JoinColumn(name="idea_id")
    private Set<Comment> comments;
    
    @Column(name="like_counter")
    private int likeCounter;
    
    @Column(name="domain_id")
    private int domainId;
    
    @Column(name="open")
    private boolean open;

    /**
     * @return the id
     */
    public Integer getId() {
        return id;
    }

    /**
     * @param id the id to set
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * @return the desc
     */
    public String getDescription() {
        return description;
    }

    /**
     * @param desc the desc to set
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * @return the userName
     */
    public String getUserName() {
        return userName;
    }

    /**
     * @param userName the userName to set
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * @return the created
     */
    public Calendar getCreated() {
        return created;
    }

    /**
     * @param created the created to set
     */
    public void setCreated(Calendar created) {
        this.created = created;
    }

    /**
     * @return the open
     */
    public boolean isOpen() {
        return open;
    }

    /**
     * @param open the open to set
     */
    public void setOpen(boolean open) {
        this.open = open;
    }

    /**
     * @return the comments
     */
    public Set<Comment> getComments() {
        return comments;
    }

    /**
     * @param comments the comments to set
     */
    public void setComments(Set<Comment> comments) {
        this.comments = comments;
    }

    /**
     * @return the pub
     */
    public boolean isPub() {
        return pub;
    }

    /**
     * @param pub the pub to set
     */
    public void setPub(boolean pub) {
        this.pub = pub;
    }

   
    /**
     * @return the domainId
     */
    public int getDomainId() {
        return domainId;
    }

    /**
     * @param domainId the domainId to set
     */
    public void setDomainId(int domainId) {
        this.domainId = domainId;
    }

    /**
     * @return the likeCounter
     */
    public int getLikeCounter() {
        return likeCounter;
    }

    /**
     * @param likeCounter the likeCounter to set
     */
    public void setLikeCounter(int likeCounter) {
        this.likeCounter = likeCounter;
    }
    
}
